/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services.route'
import { Route as ProjectsRouteImport } from './routes/projects.route'
import { Route as ProductsRouteImport } from './routes/products.route'
import { Route as AboutRouteImport } from './routes/about.route'
import { Route as IndexRouteImport } from './routes/index.route'

// Create/Update Routes

const ServicesRouteRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsRouteRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any)

const ProductsRouteRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRoute,
} as any)

const AboutRouteRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRouteRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRoute
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/about': typeof AboutRouteRoute
  '/products': typeof ProductsRouteRoute
  '/projects': typeof ProjectsRouteRoute
  '/services': typeof ServicesRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/about': typeof AboutRouteRoute
  '/products': typeof ProductsRouteRoute
  '/projects': typeof ProjectsRouteRoute
  '/services': typeof ServicesRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRouteRoute
  '/about': typeof AboutRouteRoute
  '/products': typeof ProductsRouteRoute
  '/projects': typeof ProjectsRouteRoute
  '/services': typeof ServicesRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/products' | '/projects' | '/services'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/products' | '/projects' | '/services'
  id: '__root__' | '/' | '/about' | '/products' | '/projects' | '/services'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  AboutRouteRoute: typeof AboutRouteRoute
  ProductsRouteRoute: typeof ProductsRouteRoute
  ProjectsRouteRoute: typeof ProjectsRouteRoute
  ServicesRouteRoute: typeof ServicesRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  AboutRouteRoute: AboutRouteRoute,
  ProductsRouteRoute: ProductsRouteRoute,
  ProjectsRouteRoute: ProjectsRouteRoute,
  ServicesRouteRoute: ServicesRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/products",
        "/projects",
        "/services"
      ]
    },
    "/": {
      "filePath": "index.route.tsx"
    },
    "/about": {
      "filePath": "about.route.tsx"
    },
    "/products": {
      "filePath": "products.route.tsx"
    },
    "/projects": {
      "filePath": "projects.route.tsx"
    },
    "/services": {
      "filePath": "services.route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
