/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services.route'
import { Route as ProjectsRouteImport } from './routes/projects.route'
import { Route as FaqRouteImport } from './routes/faq.route'
import { Route as IndexRouteImport } from './routes/index.route'

// Create/Update Routes

const ServicesRouteRoute = ServicesRouteImport.update({
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsRouteRoute = ProjectsRouteImport.update({
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any)

const FaqRouteRoute = FaqRouteImport.update({
  path: '/faq',
  getParentRoute: () => rootRoute,
} as any)

const IndexRouteRoute = IndexRouteImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRouteRoute,
  FaqRouteRoute,
  ProjectsRouteRoute,
  ServicesRouteRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/faq",
        "/projects",
        "/services"
      ]
    },
    "/": {
      "filePath": "index.route.tsx"
    },
    "/faq": {
      "filePath": "faq.route.tsx"
    },
    "/projects": {
      "filePath": "projects.route.tsx"
    },
    "/services": {
      "filePath": "services.route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
